### PR TITLE
Update the Game View while application is not playing

### PR DESCRIPTION
**Pull request by nxrighthere**

### CODE REVIEW

**Comment by gokselgoktas** [comment]
Hey there! Thanks a lot for the contribution, however force refreshing the Game view while not in play mode would be detrimental to the editor's performance, especially for larger projects.

**Comment by nxrighthere** [comment]
I did not find a more elegant solution. I'm just tired of manually updating the Game View every time by clicking on it...

**Comment by gokselgoktas** [comment]
I know the feeling. We could maybe add this feature as a debug option? A small checkbox in a debug box that force redraws the Game view when checked.

**Comment by nxrighthere** [comment]
Done with some optimization https://www.diffchecker.com/2kwywyfk

**Comment by gokselgoktas** [comment]
Great! If you make a PR, I'll add this!

**Pull request closed without merging**
